server:
  port: 8761  # Eureka default port

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false  # Eureka server does not register itself
    fetch-registry: false         # Eureka server does not fetch other services

  instance:
    hostname: localhost  # optional, hostname of server

# Optional: make the dashboard prettier
management:
  endpoints:
    web:
      exposure:
        include: "*"  # allows access to all actuator endpoints
